name: Testing Action
on:
    workflow_dispatch:


jobs:
    auth:
        name: Github App Auth Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Check Running
              uses: ./
              id: generate-token
              with:
                app-id: ${{ secrets.APP_ID }}
                private-key: ${{ secrets.APP_PEM }}
            
            - name: Authentication Test
              env:
                GH_TOKEN: ${{ steps.generate-token.outputs.token }}
              run: |
                gh auth status
                gh api /octocat
            
